
platform:
  - x64

cache:
  - C:\mingw64

install:

  # Take a look at the environment
  - set

  - set "PATH=C:\msys64\usr\bin;C:\msys64\mingw64\bin;%PATH%"


  - C:\msys64\usr\bin\bash -lc ""
  - C:\msys64\usr\bin\bash -lc "pacman --version"
  - C:\msys64\usr\bin\bash -lc "pacman -Q"
  # Switch from SF to msys2.org (default, much faster)
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm --sync pacman-mirrors"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S autoconf automake bison flex"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S mingw-w64-x86_64-qt4"


build_script:

  # Build Qucs-GUI applications
  # Open dummy file descriptor to fix error: ./configure: line 560: 0: Bad file descriptor

  - bash -lc "exec 0</dev/null && cd $APPVEYOR_BUILD_FOLDER/qucs && ./bootstrap"
  - bash -lc "exec 0</dev/null && cd $APPVEYOR_BUILD_FOLDER/qucs && export QTDIR=/c/msys64/mingw64/ && ./configure"
  - bash -lc "exec 0</dev/null && cd $APPVEYOR_BUILD_FOLDER/qucs && make"

  # Build Qucs-core
  - bash -lc "exec 0</dev/null && cd $APPVEYOR_BUILD_FOLDER/qucs-core && ./bootstrap"
  - bash -lc "exec 0</dev/null && cd $APPVEYOR_BUILD_FOLDER/qucs-core && ./configure"
